version: '3.9'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=replace_with_strong_secret
      - JWT_ISSUER=auth-service
      - JWT_AUDIENCE=auth-clients
      - ACCESS_TTL_SEC=900
      - REFRESH_TTL_SEC=604800
      - ENABLE_AZURE_B2C=false
      - CORS_ORIGIN=http://localhost:5173,http://localhost:3000
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
